### ISSUE TITLE
installUnbound.sh - ipv6

### ISSUE THREAD

**Issue by BulldozerPete** [Zelo72/rpi#1]
Hallo @Zelo72,

Dein Skript beinhaltet kein ipv6. Soll ich entsprechende Stellen mal anpassen und das Skript testen?

**Comment by Zelo72** [comment]
Was fehlt denn?

ipv6 ist in der unbound/pi-hole.conf konfiguriert:

# May be set to yes if you have IPv6 connectivity
    do-ip6: yes

**Comment by BulldozerPete** [comment]
Unter unkt 1 ganz unten: Das ipv6 Äquivalent für 127.0.0.1#5335.

**Comment by AleksCee** [comment]
Das ist ja nur die Anleitung wie man es im pihole hinterlegen soll, sicher kann man es via IPv4 und IPv6 hinterlegen, aber da der unbound eh nur lokal ansprechbar ist, macht das glaube ich, keinen großen Unterschied.

**Comment by BulldozerPete** [comment]
Okay.

**Comment by Zelo72** [comment]
Natürlich kann man ein _dig pi-hole.net @::1 -p 5335_ machen und _::1#5335_ als Custom 3 (IPv6) DNS in Pi-hole hinterlegen, aber wie @AleksCee gesagt hat, es macht keinen Unterschied. Die DNS-Auflösung geschieht über localhost Port 5335.
Die IPv6 anzugeben wäre nur notwendig, wenn man ein locales Netz betreiben würde in dem nur lokale IPv6 Adressen vergeben werden.
