### ISSUE TITLE
regex_ads-tracking.txt 

### ISSUE THREAD

**Issue by BulldozerPete** [Zelo72/rpi#10]
Hallo @Zelo72,

woher hast Du die ganzen RegEx Einträge?
Probierst Du die auch aus?

Grüße
BulldozerPete

**Comment by Zelo72** [comment]
Hi, ja, fahre "automatiserte" Tests mit Alexa Top Listen für DE und ermittle dann die potentiellen Domains aus den Kategorien Ads, Site Analytics und Tracking. Teste gerade ein bisschen mit AdGuardHome ...

**Comment by BulldozerPete** [comment]
Ah okay.
Wie funktioniert das Testen mit Alexan und den Top Listen für DE?
Werden z.B. die 100 beliebtesten Webseiten in DE aufgerufen und dann alle aufgerufenen URLs in einer Liste gesammelt?

**Comment by Zelo72** [comment]
Ja, erstelle mir die Top 150 und lasse sei im Browser öffnen.

Du kannst in Pihole auch [***diese Liste***](https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/regex_ads-tracking.txt) einbinden. In dieser habe ich alle RegEx mittels Sublist3r in Subdomains und TLDs umgewandelt.
In Pihole kann man ja leider keine kompletten TLDs blocken, das macht AdguadHome deutlich besser.

**Comment by Zelo72** [comment]
Hier mein Script um die Toplisten zu extrahieren:

```
#!/bin/bash

if [ -z "$1" ]; then
    n=50
else
    n=$1
fi

name=toplist.white
#sourcedir=/media/nas/git/priv/shell/blocklist
outputdir=/media/nas/tmp
#pushdir=/media/nas/git/rpi/pihole/blocklists/quellen

cd $outputdir || exit
#rm "$outputdir/$name"*

echo ""
echo "##### Toplist - $name #####"
echo ""

(
    echo ""
    echo "Downloade $name    --> "
    curl -o topsites.zip http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
    unzip topsites.zip
    rm topsites.zip

    echo ""
    echo -n "Erstelle $name    --> "
    cat <top-1m.csv | awk -F',' '{print $2}' >$name
    rm top-1m.csv
    dos2unix -q $name
    wc -l $name

    echo ""
    echo -n "Erstelle $name.de --> "
    cat <$name | grep '\.de$' | head -n $n >$name.de
    wc -l $name.de

    echo ""
    echo -n "Erstelle $name.eu --> "
    cat <$name | grep '\.eu$' | head -n $n >$name.eu
    wc -l $name.eu

    echo ""
    echo -n "Erstelle $name.nl --> "
    cat <$name | grep '\.nl$' | head -n $n >$name.nl
    wc -l $name.nl

    echo ""
    echo -n "Erstelle $name.at --> "
    cat <$name | grep '\.at$' | head -n $n >$name.at
    wc -l $name.at

    echo ""
    echo -n "Erstelle $name.ch --> "
    cat <$name | grep '\.ch$' | head -n $n >$name.ch
    wc -l $name.ch

    echo ""
    echo -n "Erstelle $name.uk --> "
    cat <$name | grep '\.uk$' | head -n $n >$name.uk
    wc -l $name.uk

    echo ""
    echo -n "Erstelle $name.net --> "
    cat <$name | grep '\.net$' | head -n $n >$name.net
    wc -l $name.net

    echo ""
    echo -n "Erstelle $name.org --> "
    cat <$name | grep '\.org$' | head -n $n >$name.org
    wc -l $name.org

    echo ""
    echo -n "Erstelle $name.com --> "
    cat <$name | grep '\.com$' | head -n $n >$name.com
    wc -l $name.com

    echo ""
    echo -n "Erstelle $name.world --> "
    cat <$name | head -n $n >$name.world
    wc -l $name.world

    echo ""
    echo "Fertig!"
    echo ""
) | tee $outputdir/$name.stats
```

Und daraus erstelle ich mir einfach eine Windows-Batch-Datei, die mir die Domains im Edge nacheiander aufruft - man muss im Edge natürlich den Adblocker und das Tracking abschalten, das soll ja PiHole oder AdGuardHome übernehmen;

```
#!/bin/bash

name=toplist.white.$1
outputdir=/media/nas/tmp

cd $outputdir || exit
dos2unix -q $name

readarray -t domains <"$name"

[ ! -s "testDomains.bat" ] || rm testDomains.bat
touch testDomains.bat

for domain in "${domains[@]}"; do
    echo "start msedge $domain" >> testDomains.bat
    echo "timeout /T 5" >> testDomains.bat
done

unix2dos -q testDomains.bat 
```

**Comment by Zelo72** [comment]
Die Domains untersuche ich dann mit AdGuardHome, er liefert Informationen zu bekannten Domains über [Whotracks.me](https://whotracks.me/), damit lassen sich potentielle nicht geblockte Domains relativ schnell erkennen:

![grafik](https://user-images.githubusercontent.com/62211544/118406751-7d0b6c80-b67d-11eb-972a-8add9a497abf.png)

**Comment by BulldozerPete** [comment]
Ah cool.
Ich nehme mal an, dass der Hauptteil der Webseiten, auf den sich die Blocklist Konsumenten hier bewegen, nicht in der Alexa Liste sind.
Vorschlag: Können wir hier eine Datei anlegen und da Webseiten eintragen, die häufig aufgerufen werden aber nicht in der Top 150 Liste enthalten sind?

**Comment by Zelo72** [comment]
Klar kann man das, brauche nur Input um welche Seiten es sich denn handelt. 

Ich habe die Seiten, die ich besuche und die Alexa Top 150 DE und COM gecheckt. Des Weiteren wandle ich gerade die TLDs aus der [Kees1958-Liste](https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_ABP) ins Pihole-Format (Sub- und TLDs-Domains) um.
Damit sollte man so gut wie alles erwischen, was in anderen Blocklisten fehlt.

Allerdings besteht natürlich die Gefahr, falsch Positive zu generieren, oder etwas zu blocken was eine Seite am Laden hindert. Ist also nur etwas für Benutzer, die den Pihole auch administrieren.

Will man sorglos ohne Werbung mit ein bisschen Privatssphärenschutz surfen ohne das irgendwas "falsches" geblockt wird oder der Pihole mit Telemetrieanfragen geflutet wird weil eine bestimmte Domain geblockt wird, empfehle ich nur die Muti- und die Fake-Liste zu verwenden, sonst nichts. Bei diesen Listen habe ich großen Wert darauf gelegt, dass "wartungsfreies" surfen ohne Werbung möglich ist und sich auch Referral-Links z.B. in der Googlesuche anklicken lassen aber trotzdem keine Werbung angezeigt wird.

**Comment by Zelo72** [comment]
Habe die [***Toplists 150*** nach TLDs](https://github.com/Zelo72/rpi/tree/master/toplists) mal zur Verfügung gestellt.

**Comment by BulldozerPete** [comment]
Okay danke.
Ich kann z.B. golem.de, GitHub.com oder computerbase.de auf den Listen nicht finden, da die nicht zu den Top 150 Webseiten in DE zählen.

**Comment by Zelo72** [comment]
Golem ist gar nicht bei den Top Sites vertreten, warum auch immer.

Computerbase ist in DE auf 103:
![grafik](https://user-images.githubusercontent.com/62211544/118410314-0bd4b500-b68f-11eb-883c-48e80388111a.png)

Github ist in COM auf 73:
![grafik](https://user-images.githubusercontent.com/62211544/118410395-830a4900-b68f-11eb-8196-83470d8b5b98.png)

**Comment by BulldozerPete** [comment]
Ich suche morgen mal die URLs raus, die auf keiner Liste stehen.

**Comment by Zelo72** [comment]
Danke, füge einfach deine Domains [***dieser Liste***](https://github.com/Zelo72/rpi/blob/master/toplists/domains.txt) mittels Pull-Request hinzu. Egal ob sie bereits auf den anderen Toplisten sind oder nicht.

**Comment by BulldozerPete** [comment]
Ich muss aber jede Liste durchsuchen, oder soll ich die Alexa zip Datei mit der csv Datei herunterladen?

**Comment by Zelo72** [comment]
Morgen, ich würde die Domains die du hast einfach auf die Liste setzen, unabhängig davon ob sie auf irgendeiner Topliste sind. So hat man eine Gesamtliste unabhängig von den Toplisten die man mal prüfen kann. Werde dann auch Domains hinzufügen.

**Comment by BulldozerPete** [comment]
Klingt nach einem guten Plan!

**Comment by Zelo72** [comment]
Ich habe die Domainliste gegen meine Multi-Liste und die Ads-RegEx gecheckt, gefunden habe ich dabei nur:
```
track.realtimeboard.com
fast.wistia.net
hello.myfonts.net
analytics.vxcdn.com
```
Wobei man wistia.net wahrscheinlich vollständig blocken könnte, also mittels RegEx.

Statistik:

![grafik](https://user-images.githubusercontent.com/62211544/118657359-b3ff9080-b7eb-11eb-9228-ad11dca0e065.png)

35% geblockt, das ist ein guter Wert.

**Comment by BulldozerPete** [comment]
Super.
Ich werde die Liste weiter ergänzen.

**Comment by BulldozerPete** [comment]
Welche URL greift denn auf https://wistia.com/ zu?
Laut der Webpage ist ihr Service: "Your complete video hosting platform for better marketing". Also Video-Werbung.

**Comment by Zelo72** [comment]
Weiß ich leider nicht mehr. Um das heraus zu finden müsste ich den Test noch mal fahren.

**Comment by Zelo72** [comment]
> Welche URL greift denn auf https://wistia.com/ zu?
Es war miro.com

**Comment by BulldozerPete** [comment]
okay

**Comment by Zelo72** [comment]
Habe noch mal gegen die Domain-Liste mit Pihole und meiner aus den vorherigen Tests ergänzten Multi-Liste getestet:
![grafik](https://user-images.githubusercontent.com/62211544/119037463-4b164500-b9b2-11eb-8849-57c1adf113b8.png)

Ich habe auch nichts "blockbares" mehr gefunden. Das sollte es erst mal gewesen sein. Ein paar falsch positve musste ich zurückdrehen, hoffe aber ich bin damit durch.

**Comment by BulldozerPete** [comment]
Ja klingt gut.
Neue Domains trage ich dann per PR in die Liste ein.

Somit sollten die häufig aufgerufenen Webseiten unter Beobachtung stehen.
Für die weitaus schwieriger zu erfassenden Domainaufrufe von Programmen habe ich noch keine Idee, da die sich ja mit jedem Softwareupdate ändern können.

**Comment by Zelo72** [comment]
Ja, aber man kann auch nicht alles blocken, Domainblocking hat seine Grenzen. Pihole macht es einem dabei nicht einfach, da kein volständiges Domain-Blocking (FLD+SLD) in Blocklisten möglich ist, dafür muss man dann auf das sehr langsame RegEX-Blocking zurück greifen. AdGuardHome kann das und ich verstehe nicht warum man das nicht in Pihole implementiert.

Overblocking führt früher ode später zu Problemen. man sucht warum Dies oder Jenes nicht funktioniert und whitelistet - das in einer Dauerschleife. Wenn du keinen Vollzeitadmin einstellen willst, musst du halt Kompromisse eingehen, einen Tot muss man sterben. Ich verfolge mit den Blocklisten genau dieses Ziel: Kein Overblocking.

**Comment by BulldozerPete** [comment]
Overblocking ist auch nicht mein Ziel.
