### ISSUE TITLE
Anleitung installUnbound.sh

### ISSUE THREAD

**Issue by BulldozerPete** [Zelo72/rpi#2]
Kannst Du bitte ein paar Anleitungszeilen in installUnbound.sh hinzufügen, ich bekomme das trotz root Rechte nicht installiert.

Danke

**Comment by Zelo72** [comment]
Was funktioniert denn nicht?

**Comment by BulldozerPete** [comment]
Das hatte ich gestern auch ausgeführt.
Nach dem sudo -i natürlich wget -N "url".

ich suche mal den Fehler raus.

**Comment by BulldozerPete** [comment]
-bash: ./installUnbound.sh: Permission denied

**Comment by AleksCee** [comment]
Mach mal ein ls -l auf die Datei ich denke der fehlen Aufführungsrechte.
chmod u+x auf die Datei könnte das beheben, wenn es das ist.

**Comment by BulldozerPete** [comment]
Jetzt geht es.
Danke @AleksCee !

**Comment by AleksCee** [comment]
@BulldozerPete nur ein kleiner Tipp am Rande - ich finde es gut, dass Du dich da so einbringst aber wenn Du fremde Scripte ausführst, solltest Du dich ein wenig mehr damit beschäftigen, als einfach nur alles runter zu laden. Guck Dir z.B. mal: https://de.wikipedia.org/wiki/Chmod an.
Am Besten wäre es sogar, den Inhalt soweit zu verstehen, dass man ein gutes Gefühlt hat, dass es keinen Schaden anrichtet.
Nur mal ein negativ-Beispiel, das richtet zwar keinen großen Schaden an, aber kann dein System komplett zum Stillstand bringen und es hat fast keinen lesbaren Code: https://de.wikipedia.org/wiki/Forkbomb#Bash
