### ISSUE TITLE
Ashampoo Lizenz

### ISSUE THREAD

**Issue by Slipi089** [Zelo72/rpi#26]
Hallo leider funktioniert mit der experimental Blocklist die Lizenzierung eines Foto Programms von Ashampoo nicht, sie blockt: licenses.ashampoo.com
Bitte auf die Whiteliste nehmen. Danke

**Comment by Zelo72** [comment]
Hi, danke, ist auf der Whitelist. Generierung der Listen läuft. Gruß, Gerd
