### ISSUE TITLE
Regex Filter für URLs benötigt

### ISSUE THREAD

**Issue by BulldozerPete** [Zelo72/rpi#5]
Hallo @Zelo72,

habe gesehen, dass Du den Regex Filter `(^|\.)unity3d\.com$` entfernt hast.
In Deinen Listen habe ich mal nach `unity3d.com` gesucht und folgendes gefunden:

ads.internal.unity3d.com
analytics.cloud.unity3d.com 
auction-master.ads.prd.ie.internal.unity3d.com 
cdn-creatives-prd.unityads.unity3d.com 
cdn-highwinds.unityads.unity3d.com 
cdn-store-icons-akamai-prd.unityads.unity3d.com 
cdn-webview-pge-geocdn-prd.unityads.unity3d.com 
china-cdn3.unityads.unity3d.com 
china-cdn.unityads.unity3d.com 
dsp-endscreens.unityads.unity3d.com 
ecommerce.iap.unity3d.com 
events.iap.unity3d.com 
httpkafka.ads.prd.ie.internal.unity3d.com 
hwstats.unity3d.com 
iap.unity3d.com 
ingress.unityads.unity3d.com 
installtracker.unityads.unity3d.com 
issuetracker.unity3d.com 
nginx-auction-legacy.ads.internal.unity3d.com 
nginx-auction-prd.ads.internal.unity3d.com 
sdk-diagnostics.prd.mz.internal.unity3d.com 
sdk-diagnostics.stg.mz.internal.unity3d.com 
staging.unityads.unity3d.com 
thind-gke-euw.prd.data.corp.unity3d.com 
tracking.adsx.unityads.unity3d.com 
www.unityads.unity3d.com

Die URLs setzen ich ja wie folgt zusammen: `abc.xyz.unity3d.com`.
Kennst Du Dich mit der Erstellung von Regex Filtern aus und kannst dafür bitte einen erstellen?

**Comment by Zelo72** [comment]
Es macht eigentlich keinen Sinn unity3d.com komplett zu sperren, deshalb habe ich das RegEx enfernt. Filtern über Blocklisten ist "the way to go".

**Comment by BulldozerPete** [comment]
Okay.
Dann mache ich das hier zu.
