### ISSUE TITLE
regex_ads

### ISSUE THREAD

**Issue by BulldozerPete** [Zelo72/rpi#9]
Hi @Zelo72,

habe alle Regex Einträge aus regex_ads in meinem Pi-hole hinzugefügt.
Jetzt wird bei mir die URL a****.dscq.akamai.net recht häufig geblockt.
In keiner meiner anderen Blocklists wird diese Domain überhaupt geblockt.

Was wird über diese URL aufgerufen?

**Comment by Zelo72** [comment]
Ich habe keine Ahnung, die wurden von einem Mitglied aus der Pihole-Telegram-Gruppe hinzugefügt. Ich verwende selbst keine RegEx.
